hash-format = "sha256"

[[files]]
file = "mods/animatica.pw.toml"
hash = "e3542efde2011e7315bb2bda8c0f32a4eda47299f82a462d2a78c93c23997752"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "2492a7266fab4c2ff411612180974b98510afb66a18e640f4de63ad615dd1e9e"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
hash = "eb0d74103b07e202b36d7e7e0957afc054d9622acf8ecb738e5856b5144a7b3b"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "378184d2642a7ed600c63b8a3f93a76255592a0f4695c992a130784f1bb2dc94"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "3c9575df506c2514c9c5e162c55dc5d5ff4a85bc50baf0c71ccbb5fe8a5105bc"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "4787f85c589daa3354184f46392382f017ac7172f543f22504ce5b8755f6f025"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "d7255889c832072601ab0a3878f5cbeb056d3bc903146074e22c5850433ee747"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "62eee72c3a020fa7e20ddb186d6831b2a8561ab8f1345b0e3bf1d3fa5322ce90"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "c652306fdcbb41d5acb22b625217b0ab31e4d8e36d61411ba74008c829046d11"
metafile = true

[[files]]
file = "mods/chisels-bits-for-fabric.pw.toml"
hash = "3dd5b0e8ffa23ab45130e40692723ad8dca91a99a114cf95d87bc5be1ab977cb"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "ae11fe7c63207b7257ecb782d421655c6f56adb551b78ad430066edc94bee3b1"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "8459128658c0148ba1b89d87b4c86bd62f236c73cff860090eba0b08e49ae9ce"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "479b3a0a2e60138458a136bf176e84131646419b20fcaade540c948183d1d351"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
hash = "7adc75eb0e53f225209b988d554e715a4765cc6adbd5e5771da5152455753638"
metafile = true

[[files]]
file = "mods/create-deco-fabric.pw.toml"
hash = "04d95de568270ce6b115aefb77dd9a8a9511398d4305f1ca2798310b75851e67"
metafile = true

[[files]]
file = "mods/create-diesel-generators-fabric.pw.toml"
hash = "10ee372d7461604db3a3ba540cd9b108c67efa025d5ac9c13ae2e69d5dad443e"
metafile = true

[[files]]
file = "mods/create-escalated.pw.toml"
hash = "b3e08d5bf0b41b72ae307144a0f645b77e1ff51593cda48e539db7d3a97171c7"
metafile = true

[[files]]
file = "mods/create-extended-bogeys-borked-addon.pw.toml"
hash = "cc5d952850fcefe9fdd5e90a5d509ca9fbb799908cf99d23ad06e7b4eac37fd6"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "c9297ce4f2d18b77e8ce81e94796f8b7e793f59f319cc574271e6e16980e23d1"
metafile = true

[[files]]
file = "mods/create-interactive.pw.toml"
hash = "b14eb5e209bdb5db0425bc2105f5ca27b0803d617df35ffbf85fadddc359e098"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "0ae145abd19c9e12c4fc5edb8ac6615811751862113395ea8145d7d7aa204019"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "210a2ac7359605a83b8601e29fb8a16ea15420db1b2f70ae068941d12daf9f50"
metafile = true

[[files]]
file = "mods/create-trainutilities.pw.toml"
hash = "eb8cd05982d086bf71c338057819a848e9b51ffdd3e1e2acd8ebbd282aa46b07"
metafile = true

[[files]]
file = "mods/create_radar-0.1.1+1.20.1.jar"
hash = "b17bd8343cc6fcbb3237ba1daccd550fb3b1e502d4a1cf8c38bdbf89cf45a462"

[[files]]
file = "mods/debugify.pw.toml"
hash = "73b57f14646c1b189bc46d07e7dc6537f6eb5b3846862e8c88d6e3ab92e63a73"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "5d01b272a43cf490d673ae9179bff0afd740b7b3884eb64be587fd7e8e0f4133"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "64812716eff60acd077307ad30922e02c967713037a8d88e4870943d0215ab6f"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "6190d61fd13e5aa8dad47af4ec7e8aa74b8edb57027efd1d37d41520e2c5a431"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "76c4b5a7d1d354d678ff27afdc45134c357933d57f889f6738ca7a9d24772508"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "1aa94f817646eea69478dc3dce662c3f4b674359d7ce34cf58fd38dcbc56e458"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "83718d6202aec5aada8fa2f790136386478f5d48d707037a43666721f00137a2"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "d15f94b721a01d87f9f714429a5a2dec23992e67d2bbafa65fc53f203f45ff1b"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "28f53f38c111e3d6aa7f6854fa976a1456f4094dc504a929a6d4bf1f9f8cc30a"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "4833d71d50426503dc98c43d1ffa85a37facb1dbbe90c52694bd784abe5f9d47"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "60adfc1ee75f10a7290e18f3e2b82601a3d3915db0c53dabe08dd17daf1c7d76"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "150b043e030da14e99ea5805c5497fe5af3981fc52d22fa1f53e4d0583449ba5"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "66d1b7bc973830475a7bae8a5b823ec42fbc1ed1f4d4c514f1e6a21b20177810"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "8fa95d727352696756f6b9b39652567317ca798c7abffff8f68480b54421dc7b"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5553f08402ff3f277f68bf132463f187d14e2b12275ae319f934e4672f4b9288"
metafile = true

[[files]]
file = "mods/ritchies-projectile-library.pw.toml"
hash = "e8057f84a7acef0c1612652ccda4f224ebbb55bd4ee6959d708e85969cdefb48"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "356a264757b1b5d0eda01c8c09ec7dd40062e93003d1e5ee027d3215eef2e0ce"
metafile = true

[[files]]
file = "mods/valkyrien-skies.pw.toml"
hash = "a1bc649de54508cd4d5f47339eb3c499f9d700d0526b8294ca102dbcbe75da8e"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "6ba47c70b307187c97f231474c30c75b56b296c7b32a49174e7314f542de2c71"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "4b5d595d3d226ad48a28bd213b32c1685b8b257f67a6617d8e9bea48d9d20001"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "eac5d5405a7020336980c31c15aab41e0a8fd6881f53deca8ad07c247e968206"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "bbbcf529b4c35f04e733922ca06dde4aac8d97a556e4396da25d99e2d079c0c9"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "0e66841d986f960b37820129ca73b60b3c7f873d147ff64485ffa5bd12213fe9"
metafile = true

[[files]]
file = "options.txt"
hash = "8dfa01382b1e738fd9ee7ce8ddcbe20fa25c4b587294924bbd51d79659ef02cd"

[[files]]
file = "packwiz-installer-bootstrap.jar"
hash = "a8fbb24dc604278e97f4688e82d3d91a318b98efc08d5dbfcbcbcab6443d116c"

[[files]]
file = "packwiz-installer.jar"
hash = "c9f646908d340d84773948a9a7d98bc1dae250d35e1016dc6e2b8459760b5598"

[[files]]
file = "resourcepacks/skt-bcg var4 v1.1.zip"
hash = "b94b5a5e92d311dc3b3cca05f286a5d2da73b992a89580ecec0b83dc41cbbe9a"
