hash-format = "sha256"

[[files]]
file = "config/DistantHorizons.toml"
hash = "232c63fd83189a4e2420791ec86b3c846032d565ed6b24b61e3edade0b8093bd"

[[files]]
file = "config/NoChatReports/NCR-Client.json"
hash = "edfe78d985fe67dce28104f3d87673e94c89134144451c291ecedcd2e2c3b480"

[[files]]
file = "config/NoChatReports/NCR-Common.json"
hash = "0eaad2630bd70ade719f7810e805810ada25379269ea194e43d3eea30c51dec0"

[[files]]
file = "config/NoChatReports/NCR-Encryption.json"
hash = "0f61ac30bfc78653a30d715f793e30a6a43d6715106706487efd0aea5d43a84c"

[[files]]
file = "config/NoChatReports/NCR-ServerPreferences.json"
hash = "df32843b853e0a493ef3a9b1e39276818294353fbb0d833f7f61e77da0f5bca1"

[[files]]
file = "config/NoChatReports/README.md"
hash = "c52b76ccad2bd1063a22c7f6bb9e7c5db6b00fb53a6fd605585972ee0e5fc01f"

[[files]]
file = "config/animatica.properties"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/bettergrass.json5"
hash = "7f2edb6c63c513d0ff5f6b216da7cc1394da4f07c192ceab805bc3ead56cc798"

[[files]]
file = "config/betterpingdisplay.json"
hash = "d9b413555ca6e7add44924c507e5ec5dc8db060f9b04fdfefcd505e61faec0e0"

[[files]]
file = "config/bobby.conf"
hash = "b53c14bbef682afb9ad89d42e06c06f093d63923661bb685f6686011f71bbb53"

[[files]]
file = "config/cardinal-components-api.properties"
hash = "f7e7f346e0724cf9cfb77f44dec2e7d202ea2507729ec7b95ee6a8f089c82982"

[[files]]
file = "config/chiselsandbits-client.json"
hash = "8434946b66fefacc628cf93c7a9032ff718301ee4b6db309fd5c9d61c9ab3a12"

[[files]]
file = "config/chiselsandbits-common.json"
hash = "1850f73cb1e59f441b2b2273843499437e5acd34a28205a100cf41b46e47638f"

[[files]]
file = "config/chiselsandbits-server.json"
hash = "980171ca682011053caf5d286034bab9a5fd28a59ff0a24189ed627eeee1d419"

[[files]]
file = "config/copycats-client.toml"
hash = "70a02fe59453e5b8ad07512adf5feb85fff05bfc3c615349f13d429496f9f7ea"

[[files]]
file = "config/copycats-common.toml"
hash = "4882fa59145fb3ee044556aa781b73342ee99d74087ea359ea86c3c8906b015d"

[[files]]
file = "config/create-client.toml"
hash = "74dbce3a70ab7968720af1b138b93a2baef8d2c7e6bfa113f58735cfabb7310e"

[[files]]
file = "config/create-common.toml"
hash = "6c0f6254798808bce8079a1cfafe4d6c082cead42c51d1e3121f3580f8a44eca"

[[files]]
file = "config/create-server-1.toml.bak"
hash = "7fed1136baf38015c32b31b0a5270c1625d17286ccb295ae6a19c82c3097b12a"

[[files]]
file = "config/create-server.toml"
hash = "a3934014ad63e09de186798a1a5831332b699adde61ea82512a4ff689083432a"

[[files]]
file = "config/create_interactive-client.toml"
hash = "7f748315fea7e5199c5a39f61a915bead6536a8dcbc7f2625fc350077b0f194c"

[[files]]
file = "config/create_interactive-common.toml"
hash = "ec7ceee769fa178b8b558e3f0ce99f2ff0a5d56d8d96f5eaf0154507959823a0"

[[files]]
file = "config/create_interactive-server.toml"
hash = "a13dee6114133cb44c33a6a8c0bab5e7b074393a1483b1fdbca3af50283ff87b"

[[files]]
file = "config/create_new_age-client.toml"
hash = "f231448f6be3eadfcc13545b90915434692d43159803424f635d5790b0b5e4ae"

[[files]]
file = "config/create_new_age-common.toml"
hash = "df99657044655d51d8e688683b537452b7df446d7589ac794cbddb841823b977"

[[files]]
file = "config/create_radar-client.toml"
hash = "fac57a1f4c9659d2d6d455cca5c72fe05d15d8e85b4cb8b0dd3b8142e67dc9a2"

[[files]]
file = "config/create_radar-server.toml"
hash = "a931f107b5e907a8ba1288a11697a5a851558dbde14bb3181e013d60cdc1af68"

[[files]]
file = "config/createaddition-common.toml"
hash = "13e84562eea7b6019f2180748cc62c167490ff7560c610d5137bca56cfdbbba5"

[[files]]
file = "config/createbigcannons-client.toml"
hash = "0fab875c08d2556853ae96c96973dc9c29a8bd30834b76fbcdde81a62d931108"

[[files]]
file = "config/createbigcannons-common.toml"
hash = "01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b"

[[files]]
file = "config/createbigcannons-server.toml"
hash = "93bbe03b397ef285cd18a78c74f1442fb3b0c4b840f38d1cdd77dd3e148adf45"

[[files]]
file = "config/createdieselgenerators-client.toml"
hash = "1bc8aaed25355536a3d2e39138d6b9a78ebe8b651cd548dd7497b59072644aff"

[[files]]
file = "config/createdieselgenerators-server.toml"
hash = "f8d5f16d875ed6780aadf2bd09d8289443fe0226c2e68706d0f5e30b19f50764"

[[files]]
file = "config/debugify-descriptions.json"
hash = "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"

[[files]]
file = "config/debugify.json"
hash = "b7651c21ec5a9a30267b76898932f51dc2f7a9efa5220e45450d7340ea6574a7"

[[files]]
file = "config/dynamic_fps.json"
hash = "ca3d163bab055381827226140568f3bef7eaac187cebd76878e0b63e9e442356"

[[files]]
file = "config/entity_model_features.json"
hash = "5ba15e6be08f7af62d0776ce1a570033d53e1be14fb5d573f22a6f7c76c8a52f"

[[files]]
file = "config/entity_texture_features.json"
hash = "0554c0e7816266477c65c18d2ada9fdddf1c6750787efd329056223ca4a073b2"

[[files]]
file = "config/escalated-server.toml"
hash = "b53a6f02220169ed47602498804d8613e90ce5edb20b086f8480dc92f7e6d04d"

[[files]]
file = "config/etf_warnings.json"
hash = "a5ba22e63061c1fb67f0f895f17681351eaeccc225faef966c29ee630593275e"

[[files]]
file = "config/fabric/indigo-renderer.properties"
hash = "e71a9ffee97d7ee9b3edcf950dba908ef5b42682648c613ffcc7d854f169378c"

[[files]]
file = "config/fastquit.toml"
hash = "8c3ed3c40bcd66d188c89503c11886f5767216c43c8c2580174e84ac79df7683"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "3cc3011619f098fda6ad213a7c4d1468802ff827591a5917c2b7bf3150bfb2ea"

[[files]]
file = "config/flywheel.json"
hash = "aa84b01d7366b116d590d52adff2acef9212f9395eb53e9db9fa9090c6a9b02d"

[[files]]
file = "config/forgeconfigapiport.toml"
hash = "da82326e21db344255a22d1dd09b104a039719c94ab3a9e64e1c71ca378ea7a1"

[[files]]
file = "config/immediatelyfast.json"
hash = "f2b7f219198f0a911d04b09f545f2c1256e8d114951443924878dc10963e16aa"

[[files]]
file = "config/indium-renderer.properties"
hash = "19aba80f82ab21b4196c9162a373dea1dcbcaab160b7b4aa1b9e10ef518710ee"

[[files]]
file = "config/lithium.properties"
hash = "76765e8e5ff8e927d80beb0739aababcf36e7babfd94262f2afece256cc5cd2e"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "94eaec2a459f27b9e5726bd83c70584476b26705a1c0479dcd6eddaa46f1962e"

[[files]]
file = "config/modmenu.json"
hash = "748cb550ed31f0d7f2a8faf26cd0c659826ae10cfabc4a89eee7d32eed98f157"

[[files]]
file = "config/moreculling.toml"
hash = "53ac845470aa4752db3537173905ca24d51799463273463e91ab5f45deb0c603"

[[files]]
file = "config/ponder-client.toml"
hash = "13cfd5766d28bcac1b95156fb48fa49af400509ca7865f88dd630854cead6aa4"

[[files]]
file = "config/railways-client.toml"
hash = "979bf4027b69affd04bd0f4afa67321b7a2c742321728d366175ad816dd5c031"

[[files]]
file = "config/railways-common.toml"
hash = "58f7821842631af9ec8bcaddb60526b81cd1b9ad63cbba87c83c70e53c3a9b16"

[[files]]
file = "config/railways-server.toml"
hash = "f51c2ccfc85e3818106753382e45bf3201dc4c88ab5d20a442b39ca3a68abf66"

[[files]]
file = "config/ritchiesprojectilelib-server.toml"
hash = "bd2ff5fb308c6648b18322b2a2d8bfc164027289ff5edbd72a7737b7e5dd822b"

[[files]]
file = "config/sodium-fingerprint.json"
hash = "48437553c40350d6e1585c6512b26345daab1e23a4c69ae566a13be0c555fbbb"

[[files]]
file = "config/sodium-mixins.properties"
hash = "8939df3a10627cf3b9a3cc0e2824337923e9a26d11e60f5a1f7c0cfbd171a574"

[[files]]
file = "config/sodium-options.json"
hash = "e170cafd722ce62aa061d6770af08274391dd17064f58e82e2ff84af2b1f95ac"

[[files]]
file = "config/valkyrienskies/schemas/vs_client.schema.json"
hash = "18ab8a80bb24a7a448e9689f6ec93921f47072b62271ae0c6d7fdf2da4a12078"

[[files]]
file = "config/valkyrienskies/schemas/vs_common.schema.json"
hash = "f5ba425afee7c543f9e010c34c451817bb9c745ffd45106fac5544e9eacadf96"

[[files]]
file = "config/valkyrienskies/schemas/vs_core_server.schema.json"
hash = "a09eb410f6b56c65904aaf5d75d74ebf67d8ed96f9d992f322e8e03fd86b1f6d"

[[files]]
file = "config/valkyrienskies/schemas/vs_server.schema.json"
hash = "48fbb6a80fd3ce3d745277844227fbc93a150473fdeb05d3417a2635adc4b0e6"

[[files]]
file = "config/valkyrienskies/valkyrienskies-client.toml"
hash = "620a8ee9068578e399651fe61e877cd6423e599cab0d9cd4236bfd0bcf0c071f"

[[files]]
file = "config/valkyrienskies/valkyrienskies-common.toml"
hash = "0b23797166d41ac0dfd91761a2a3390315ed699820aca833b174da67db92ee67"

[[files]]
file = "config/valkyrienskies/vs_client.json"
hash = "744609ee3e824e694dbc68125a2f6c1933f98d321755019e3a462a5de67fde44"

[[files]]
file = "config/valkyrienskies/vs_common.json"
hash = "b79fd15ca7286dcfa731ca333f6cffe160a46225e41479cc968dd5d8e24df3a8"

[[files]]
file = "config/valkyrienskies/vs_core_server.json"
hash = "d5b844f63b888a7ca8bec51f647727fc0ceb44df540d80865ca62e5ecf67327a"

[[files]]
file = "config/valkyrienskies/vs_server.json"
hash = "80655dd5d54b97b3784a47e84eebd1090a463cb588f9fcbfd5fd57f52eb3d277"

[[files]]
file = "config/xaero/lib/client.cfg"
hash = "43ed9dbfa5b4d6f0f3d2e8c2ced17ad298164b22c68ff11d415257a39b074336"

[[files]]
file = "config/xaero/lib/common.cfg"
hash = "98f698d96a6d21d830a455b4ad045b70516fa63c298021742d8499e7f0366cd2"

[[files]]
file = "config/xaero/lib/profiles/default.cfg"
hash = "34ae854b17d896d7cb853bdc28c27231a3947e91cb9f0991f372846ee3c2a907"

[[files]]
file = "config/xaero/lib/server_profiles/default.cfg"
hash = "d438aea41ca41e93697e059f523686935c0add482f6abe96b532bbf10c6ed80a"

[[files]]
file = "config/xaero/minimap/client.cfg"
hash = "c0915eff5d1a7905cd1038d646eb9086fd1a29e2f637d53535e4da161de17b9f"

[[files]]
file = "config/xaero/minimap/common.cfg"
hash = "2b49df024c03a369c62a303c72755e7fedeb4f4653ff53a12fd37bd83ccd4ed0"

[[files]]
file = "config/xaero/minimap/default_radar_categories_client.json"
hash = "a4c13e76500473fe8d555225022542d0ef89708c3d885e233dca15f91e437774"

[[files]]
file = "config/xaero/minimap/default_radar_categories_server.json"
hash = "a4c652cafa7dea324e5f5cf3b1df46a84e54b6d4f877195857bce55a559c1cfd"

[[files]]
file = "config/xaero/minimap/profiles/default.cfg"
hash = "db49c4dde15db318eb25e8a43fa06992778f0e17b3a963fff5cbee35da11fb81"

[[files]]
file = "config/xaero/minimap/profiles/info_display_config/default.cfg.txt"
hash = "184e654fa1fc8ad09943c97c4e65ab78acb5b3cfca22417a831513d1b6d9bbc6"

[[files]]
file = "config/xaero/minimap/server_profiles/default.cfg"
hash = "d438aea41ca41e93697e059f523686935c0add482f6abe96b532bbf10c6ed80a"

[[files]]
file = "config/xaero/world-map/client.cfg"
hash = "deece0fe0d29f2203a9699143a6209c451e91d7ecb799489c328b0d0fa31a90d"

[[files]]
file = "config/xaero/world-map/common.cfg"
hash = "0c229eb0daf85bd09af51f21eeeb99497a3bd50a825d5ab1ca695fb21bf6cf9d"

[[files]]
file = "config/xaero/world-map/profiles/default.cfg"
hash = "7b24c882801bcc7f0a8aedc625d419f661fa490fa0e9d5ebe39599a1ce2dcbd5"

[[files]]
file = "config/xaero/world-map/server_profiles/default.cfg"
hash = "d438aea41ca41e93697e059f523686935c0add482f6abe96b532bbf10c6ed80a"

[[files]]
file = "config/xaerohud.txt"
hash = "cece60604b8de5e978141c981c1ed85227c8f30697a513869012b06dd15fcf02"

[[files]]
file = "config/xaeropatreon.txt"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/yacl.json5"
hash = "d26a63d3cdf326412ba86dcc2781060bc53ed6c74ac7808e65325452e264e820"

[[files]]
file = "config/yosbr/options.txt"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/zoomify.json"
hash = "a7ccc02565cfc01be9d711b4149bf14d9c458c06c49ef1dde424afebb65ba208"

[[files]]
file = "mods/animatica.pw.toml"
hash = "e3542efde2011e7315bb2bda8c0f32a4eda47299f82a462d2a78c93c23997752"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "2492a7266fab4c2ff411612180974b98510afb66a18e640f4de63ad615dd1e9e"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
hash = "eb0d74103b07e202b36d7e7e0957afc054d9622acf8ecb738e5856b5144a7b3b"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "378184d2642a7ed600c63b8a3f93a76255592a0f4695c992a130784f1bb2dc94"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "3c9575df506c2514c9c5e162c55dc5d5ff4a85bc50baf0c71ccbb5fe8a5105bc"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "4787f85c589daa3354184f46392382f017ac7172f543f22504ce5b8755f6f025"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "d7255889c832072601ab0a3878f5cbeb056d3bc903146074e22c5850433ee747"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "62eee72c3a020fa7e20ddb186d6831b2a8561ab8f1345b0e3bf1d3fa5322ce90"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "c652306fdcbb41d5acb22b625217b0ab31e4d8e36d61411ba74008c829046d11"
metafile = true

[[files]]
file = "mods/chisels-bits-for-fabric.pw.toml"
hash = "3dd5b0e8ffa23ab45130e40692723ad8dca91a99a114cf95d87bc5be1ab977cb"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "ae11fe7c63207b7257ecb782d421655c6f56adb551b78ad430066edc94bee3b1"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "8459128658c0148ba1b89d87b4c86bd62f236c73cff860090eba0b08e49ae9ce"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "479b3a0a2e60138458a136bf176e84131646419b20fcaade540c948183d1d351"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
hash = "7adc75eb0e53f225209b988d554e715a4765cc6adbd5e5771da5152455753638"
metafile = true

[[files]]
file = "mods/create-deco-fabric.pw.toml"
hash = "04d95de568270ce6b115aefb77dd9a8a9511398d4305f1ca2798310b75851e67"
metafile = true

[[files]]
file = "mods/create-diesel-generators-fabric.pw.toml"
hash = "10ee372d7461604db3a3ba540cd9b108c67efa025d5ac9c13ae2e69d5dad443e"
metafile = true

[[files]]
file = "mods/create-escalated.pw.toml"
hash = "b3e08d5bf0b41b72ae307144a0f645b77e1ff51593cda48e539db7d3a97171c7"
metafile = true

[[files]]
file = "mods/create-extended-bogeys-borked-addon.pw.toml"
hash = "cc5d952850fcefe9fdd5e90a5d509ca9fbb799908cf99d23ad06e7b4eac37fd6"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "c9297ce4f2d18b77e8ce81e94796f8b7e793f59f319cc574271e6e16980e23d1"
metafile = true

[[files]]
file = "mods/create-interactive.pw.toml"
hash = "b14eb5e209bdb5db0425bc2105f5ca27b0803d617df35ffbf85fadddc359e098"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "0ae145abd19c9e12c4fc5edb8ac6615811751862113395ea8145d7d7aa204019"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "210a2ac7359605a83b8601e29fb8a16ea15420db1b2f70ae068941d12daf9f50"
metafile = true

[[files]]
file = "mods/create-trainutilities.pw.toml"
hash = "eb8cd05982d086bf71c338057819a848e9b51ffdd3e1e2acd8ebbd282aa46b07"
metafile = true

[[files]]
file = "mods/create_radar-0.1.1+1.20.1.jar"
hash = "b17bd8343cc6fcbb3237ba1daccd550fb3b1e502d4a1cf8c38bdbf89cf45a462"

[[files]]
file = "mods/debugify.pw.toml"
hash = "73b57f14646c1b189bc46d07e7dc6537f6eb5b3846862e8c88d6e3ab92e63a73"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "5d01b272a43cf490d673ae9179bff0afd740b7b3884eb64be587fd7e8e0f4133"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "64812716eff60acd077307ad30922e02c967713037a8d88e4870943d0215ab6f"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "6190d61fd13e5aa8dad47af4ec7e8aa74b8edb57027efd1d37d41520e2c5a431"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "76c4b5a7d1d354d678ff27afdc45134c357933d57f889f6738ca7a9d24772508"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "1aa94f817646eea69478dc3dce662c3f4b674359d7ce34cf58fd38dcbc56e458"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "83718d6202aec5aada8fa2f790136386478f5d48d707037a43666721f00137a2"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "d15f94b721a01d87f9f714429a5a2dec23992e67d2bbafa65fc53f203f45ff1b"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "28f53f38c111e3d6aa7f6854fa976a1456f4094dc504a929a6d4bf1f9f8cc30a"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "4833d71d50426503dc98c43d1ffa85a37facb1dbbe90c52694bd784abe5f9d47"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "60adfc1ee75f10a7290e18f3e2b82601a3d3915db0c53dabe08dd17daf1c7d76"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "150b043e030da14e99ea5805c5497fe5af3981fc52d22fa1f53e4d0583449ba5"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "66d1b7bc973830475a7bae8a5b823ec42fbc1ed1f4d4c514f1e6a21b20177810"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "8fa95d727352696756f6b9b39652567317ca798c7abffff8f68480b54421dc7b"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5553f08402ff3f277f68bf132463f187d14e2b12275ae319f934e4672f4b9288"
metafile = true

[[files]]
file = "mods/ritchies-projectile-library.pw.toml"
hash = "e8057f84a7acef0c1612652ccda4f224ebbb55bd4ee6959d708e85969cdefb48"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "356a264757b1b5d0eda01c8c09ec7dd40062e93003d1e5ee027d3215eef2e0ce"
metafile = true

[[files]]
file = "mods/valkyrien-skies.pw.toml"
hash = "a1bc649de54508cd4d5f47339eb3c499f9d700d0526b8294ca102dbcbe75da8e"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "6ba47c70b307187c97f231474c30c75b56b296c7b32a49174e7314f542de2c71"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "4b5d595d3d226ad48a28bd213b32c1685b8b257f67a6617d8e9bea48d9d20001"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "eac5d5405a7020336980c31c15aab41e0a8fd6881f53deca8ad07c247e968206"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "bbbcf529b4c35f04e733922ca06dde4aac8d97a556e4396da25d99e2d079c0c9"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "0e66841d986f960b37820129ca73b60b3c7f873d147ff64485ffa5bd12213fe9"
metafile = true

[[files]]
file = "options.txt"
hash = "8dfa01382b1e738fd9ee7ce8ddcbe20fa25c4b587294924bbd51d79659ef02cd"

[[files]]
file = "packwiz-installer-bootstrap.jar"
hash = "a8fbb24dc604278e97f4688e82d3d91a318b98efc08d5dbfcbcbcab6443d116c"

[[files]]
file = "packwiz-installer.jar"
hash = "c9f646908d340d84773948a9a7d98bc1dae250d35e1016dc6e2b8459760b5598"

[[files]]
file = "resourcepacks/skt-bcg var4 v1.1.zip"
hash = "b94b5a5e92d311dc3b3cca05f286a5d2da73b992a89580ecec0b83dc41cbbe9a"
