name = "witt≈Øv modpack"
author = "brzykovec"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58c24a07e91f22f1b2aa25c32a25811ad45c61b95f6d66ccaad116cc47dce242"

[versions]
fabric = "0.16.13"
minecraft = "1.20.1"
