name = "witt≈Øv modpack"
author = "brzykovec"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca84b3002fdfffae643d1d51e59122793c4da09e3011cdd0f4caff99356a6180"

[versions]
fabric = "0.16.13"
minecraft = "1.20.1"
